name: Comment Example

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: github-comment
        run: |
          wget "https://github.com/suzuki-shunsuke/github-comment/releases/download/v6.0.3/github-comment_6.0.3_linux_amd64.tar.gz" -O /tmp/github-comment.tar.gz
          tar xzf /tmp/github-comment.tar.gz -C /tmp
          mv /tmp/github-comment /usr/local/bin
          github-comment --version
      - name: sample comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo hello | github-comment post -stdin-template
